In [1]:
import aesara
import aesara.tensor as at

In [2]:
at.alloc(5, 2,2).eval()

array([[5, 5],
       [5, 5]], dtype=int8)

In [3]:
import pymc3 as pm

In [8]:
at.alloc(at.square(0.1), 10, 10)

Alloc.0

In [9]:
from pymc3.gp.cov import Covariance

In [45]:
class Constant():
    
    def __init__(self, c):
        #super().__init__(1, None)
        self.c = c
        
    def diag(self, X):
        return at.alloc(self.c, X.shape[0])
    
    def full(self, X, Xs=None):
        if Xs is None:
            return at.alloc(self.c, X.shape[0], X.shape[0])
        else:
            return at.alloc(self.c, X.shape[0], Xs.shape[0])

In [29]:
const = Constant(0.1)

In [30]:
import numpy as np

In [31]:
const.full(np.arange(10), np.arange(2)).eval()

array([[0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1]])

In [33]:
from pymc3.gp.util import cholesky, stabilize
from pymc3.gp.cov import Constant, Covariance

In [34]:
with pm.Model() as model:
    # Specify the covariance function.
    cov_func = pm.gp.cov.Constant(0.1)
    #stabilize(cov_func)

In [60]:
X = np.arange(10)

In [94]:
at.eye(10).eval()

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [109]:
at.slinalg.cholesky(cov).eval().shape

(10, 10)

In [110]:
v.shape

(10, 1)

In [107]:
with pm.Model() as model:
    mu = pm.gp.mean.Zero()
    cov = Constant(0.1).full(X) + at.eye(10).eval()*0.1
    print(cov.eval().shape)
    v = pm.Normal('_rotated_', mu=0.0, sigma=1.0, shape=10)
    print(v.distribution.logp([5.,5.,5.,5.,5.,5.,5.,5.,5.,5.]).eval().reshape((-1,1)).shape)
    v = v.distribution.logp([5.,5.,5.,5.,5.,5.,5.,5.,5.,5.]).eval().reshape((-1,1))
    print(at.slinalg.cholesky(cov).eval().shape)
    g = pm.Deterministic('g', at.slinalg.cholesky(cov).eval() @ v)
    #f = pm.Deterministic('f', mu + cholesky(cov).dot(v))
    

(10, 10)
(10, 1)
(10, 10)


ValueError: order must be one of 'C', 'F', 'A', or 'K' (got 'g')

In [39]:
cov